export class Domicilio{
    id:string;
    calle:string;
    codigoPostal:string;
    numero:number;
    piso:number;
    latitud:number;
    longitud:number;
    idLocalidad:string;
    constructor(id,calle,codigoPostal,numero,piso,latitud,longitud,localidad){
        this.id=id;
        this.calle=calle;
        this.codigoPostal=codigoPostal;
        this.numero=numero;
        this.piso=piso;
        this.latitud=latitud;
        this.longitud=longitud;
        this.idLocalidad=localidad;
    }
}